# Pipline parameters
device: CPU:0
engine: tensor
multiprocessing: false

# Camera parameters
img_width: 640
img_height: 480
fps: 30
depth_min: 0.1
depth_max: 10.0

# Scene update parameters
voxel_size: 0.0232
block_resolution: 16
trunc_voxel_multiplier: 8.0
est_point_count: 10000000
block_count: 100000
point_weight_thr: 3.0
surface_weight_thr: 3.0
wait_frames: 10
update_mesh_surface: true
raycast_box: true
do_semantic: true
recolorize: true
use_kde: true

# GUI options
win_width: 1100
win_height: 1080
skip_frames: 9
trajectory_interval: 7

# Segmentation model configurations
seg_model: 'models/yolov8n-seg.pt'
seg_device: 'cuda'

# Running option
save_data: false
save_folder: 'cap_data'
save_mesh: true
save_traj_log: false
